approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

logFilters:
  - level: discard
    text: ESM support for PnP uses the experimental loader API and is therefore experimental

yarnPath: .yarn/releases/yarn-4.14.1.cjs
