approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

logFilters:
  - level: discard
    text: ESM support for PnP uses the experimental loader API and is therefore experimental

npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.15.0.cjs
