services:
    api:
        build:
            context: ../../api
            dockerfile: .cloud/docker/Dockerfile
            target: api-dev
        image: codeclarityce/api-dev:latest
        restart: always
        command: pnpm run start:debug
        env_file:
            - ../../.cloud/env/.env.dev
        environment:
            - PNPM_STORE_DIR=/pnpm/store
        volumes:
            - ../../api:/app
            - ../../.cloud/env:/app/env
            - ../../private:/private
            - ../../scripts:/scripts
            - pnpm-store:/pnpm/store
        ports:
            - 9229:9229
            - 3000:3000
        depends_on:
            rabbitmq:
                condition: service_healthy
            db:
                condition: service_started
            adminer:
                condition: service_started
        deploy:
            resources:
                limits:
                    cpus: '4'
                    memory: 4G
                reservations:
                    cpus: '2'
                    memory: 4G
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    pnpm-store:
        external: true
